### ISSUE TITLE
WebContent

### ISSUE THREAD

**Issue by baksas** [weigo/NWDI-Sonar-Plugin#1]
Hello. Since many NWDI projects are being build with UI5.I think Sonar plugin should include WebContent as source. I simply added line <source>${basedir}/WebContent</source> to pom.vm.

**Comment by weigo** [comment]
Analysis of Javascript sources would require a second run with a different configuration:
- another set of source directories, i.e. ${basedir}/WebContent
- another language instead of java.

**Comment by baksas** [comment]
Thank You!
